(...)
bubbles:(...)
button:(...)
buttons:(...)
cancelable:(...)
clientX:(...)
clientY:(...)
ctrlKey:(...)
currentTarget:(...)
defaultPrevented:(...)
detail:(...)
dispatchConfig:null
eventPhase:(...)
getModifierState:(...)
isDefaultPrevented:null
isPropagationStopped:null
isTrusted:(...)
metaKey:(...)
nativeEvent:(...)
pageX:(...)
pageY:(...)
relatedTarget:(...)
screenX:(...)
screenY:(...)
shiftKey:(...)
target:(...)
timeStamp:(...)
type:(...)
view:(...)
_dispatchInstances:null
_dispatchListeners:null
_targetInst:null
preventDefault:(...)
stopPropagation:(...)
get altKey:ƒ ()
set altKey:ƒ (val)
get bubbles:ƒ ()
set bubbles:ƒ (val)
get button:ƒ ()
set button:ƒ (val)
get buttons:ƒ ()
set buttons:ƒ (val)
get cancelable:ƒ ()
set cancelable:ƒ (val)
get clientX:ƒ ()
set clientX:ƒ (val)
get clientY:ƒ ()
set clientY:ƒ (val)
get ctrlKey:ƒ ()
set ctrlKey:ƒ (val)
get currentTarget:ƒ ()
set currentTarget:ƒ (val)
get defaultPrevented:ƒ ()
set defaultPrevented:ƒ (val)
get detail:ƒ ()
set detail:ƒ (val)
get eventPhase:ƒ ()
set eventPhase:ƒ (val)
get getModifierState:ƒ ()
set getModifierState:ƒ (val)
get isTrusted:ƒ ()
set isTrusted:ƒ (val)
get metaKey:ƒ ()
set metaKey:ƒ (val)
get nativeEvent:ƒ ()
set nativeEvent:ƒ (val)
get pageX:ƒ ()
set pageX:ƒ (val)
get pageY:ƒ ()
set pageY:ƒ (val)
get relatedTarget:ƒ ()
set relatedTarget:ƒ (val)
get screenX:ƒ ()
set screenX:ƒ (val)
get screenY:ƒ ()
set screenY:ƒ (val)
get shiftKey:ƒ ()
set shiftKey:ƒ (val)
get target:ƒ ()
set target:ƒ (val)
get timeStamp:ƒ ()
set timeStamp:ƒ (val)
get type:ƒ ()
set type:ƒ (val)
get view:ƒ ()
set view:ƒ (val)
get preventDefault:ƒ ()
set preventDefault:ƒ (val)
get stopPropagation:ƒ ()
set stopPropagation:ƒ (val)
__proto__:SyntheticUIEvent